### ISSUE TITLE
What is the goal of this repository?

### ISSUE THREAD

**Issue by syedaliasad649** [GuptaDiva/TrailBlazer786#1]
what noble goal should we contribute towards?

**Comment by GuptaDiva** [comment]
Its goal is to serve as a medium for contributing to the open source.

**Comment by GuptaDiva** [comment]
Feel free to answer the questions provided, we will keep on updating those questions.
There is no restriction, you can solve the programs in any language.

**Comment by GuptaDiva** [comment]
Answer the questions and contribute in the hacktoberfest
